### ISSUE TITLE
dominvrt.si##.reveal-overlay causes breakage

### ISSUE THREAD

**Issue by crssi** [betterwebleon/slovenian-list#11]
The rule `dominvrt.si##.reveal-overlay` prevents the imageset to expand/zoom at https://www.dominvrt.si/rubrika/dom/domovi-slavnih/nikki-sixx-prodaja-hisa-dvorec-kalifornija.html

Lep pozdrav 😉

**Comment by betterwebleon** [comment]
Hello, fixed: d75de52

Hvala!
