### ISSUE TITLE
Nekaj predlogov

### ISSUE THREAD

**Issue by randomtroller** [betterwebleon/slovenian-list#12]
Sledilnik na Telekomovi strani:
`/track.js$domain=www.telekom.si|telekom.si` 

Arnes analitika:
`*$script,domain=analitika.arnes.si` 

Obvestilo za piškotke na eAsistentu:
`www.easistent.com##.piskotki-info-box > .row`

Reklama za spletno trgovino:
`novice.svet24.si##.bg-najnakupi-blue-light.pb-2.mt-4`

**Comment by betterwebleon** [comment]
Hvala za predloge. Urejeno: 5ccfd7c

Spodaj še nekaj pojasnil.

Sledenje na Arnesu se blokira z že obstoječim filtrom: `/piwik.js`
Kolikor sem gledal, je to edina sledilna skripta iz domen `analitika.arnes.si` in `stats.arnes.si`. Prosim za popravek, če se morda motim.

eAsistent - obvestil za piškotke se s slovensko listo načeloma ne blokira. Razlogov za to je več: teh obvestil je ogromno, z njihovim odpravljanjem se specializirano ukvarjajo že drugi. Poleg tega večino tovrstnih obvestil precej učinkoviteje blokira recimo dodatek "I don't care about cookies". Ta dodatek je na voljo za vse uveljavljene brskalnike, link: [www.i-dont-care-about-cookies.eu](https://www.i-dont-care-about-cookies.eu/#install) Ta rešitev se lahko uvozi tudi v adblocker v obliki povezave na spodnji seznam filtrov, kar sicer ni tako priporočljivo:
`https://www.i-dont-care-about-cookies.eu/abp/`
Tistih nekaj pravil za blokiranje obvestil za piškotke, ki so trenutno na slovenski listi, pa je tam samo kot dopolnilo tej zgornji rešitvi, ker jih le-ta zaenkrat še ne blokira.

**Comment by randomtroller** [comment]
Glede Arnesa res nisem vedel, se opravičujem za filter proti obvestilu za piškotke.

**Comment by betterwebleon** [comment]
Ni problema, hvala za poslano! 👍
