### ISSUE TITLE
Nekaj predlogov, ki izhajajo iz strani https://klikponudba.com

### ISSUE THREAD

**Issue by crssi** [betterwebleon/slovenian-list#14]
Na strani `https://klikponudba.com` je "en mali miljon" sumljivih 3p povezav.
Več informacij najdete tukaj: `https://github.com/badmojr/1Hosts/issues/59#issuecomment-745034513`
```
d1u9wuqimc88kc.cloudfront.net
cdn-spurit.com
wheelioapp.azureedge.net
boostercentral.com
multifbpixels.website
sp-seller.webkul.com
window-shoppers.azurewebsites.net
boostifytheme.com
cdn.ghostmonitor.com
dashboard.wheelio-app.com
sr-cdn.azureedge.net
disco-flipclock.netlify.app
cdn.judge.me
```

Lep pozdrav

**Comment by crssi** [comment]
Dodatno na zgornjo listo:
```
monorail-edge.shopifysvc.com
easygdpr.b-cdn.net
cdn.codeblackbelt.com
cdn.pushowl.com
sy.salesmanago.pl
```

**Comment by betterwebleon** [comment]
Hvala za poslano. Kaže, da je tole zrelo za kakšno hosts listo – kot si že javil na 1Hosts. Sporočeno tudi na:
- https://github.com/StevenBlack/hosts/issues/1490
- https://forums.lanik.us/viewtopic.php?f=62&t=45534 (razen domene `sy.salesmanago.pl`, ki je blokirana z EasyPrivacy na osnovi filtra `||salesmanago.pl^$third-party`)
