### ISSUE TITLE
ADS ponudnik dnetwork.si

### ISSUE THREAD

**Issue by crssi** [betterwebleon/slovenian-list#16]
`https://dnetwork.si/` je očitno ADS ponudnik, ki ponuja preko naslova `dmb.dnetwork.si`.

Žal sem "založil" primer strani.
Če bo potrebno, ga dodatno sporočim, ko ponovno najdem.

Lep pozdrav

**Comment by betterwebleon** [comment]
Hvala, urejeno: f3d991e

Če je možno, lahko sporočiš primer strani, za evidenco.

Lep pozdrav
