### ISSUE TITLE
Arnes AAI prijava

### ISSUE THREAD

**Issue by randomtroller** [betterwebleon/slovenian-list#17]
Na ds.aai.arnes.si je element, ki se kliče consent-container in ga filtri proti obvestilom za piškotke blokirajo. Element nima nič zveze s piškotki in je potreben za izbor domače organizacije. (slika https://i.postimg.cc/63VGDxDW/consent-container.png). Filtri proti piškotkom naredijo to https://i.postimg.cc/MHvq1y0C/blokirano.png

`@@||ds.aai.arnes.si$generichide` je edina rešitev, ki sem jo našel.

**Comment by betterwebleon** [comment]
Lahko pogledaš, kateri seznam filtrov blokira ta `consent-container` element? Sam ne uporabljam tovrstnih seznamov za blokiranje piškotkov (razen razširitve za skrivanje obvestil o piškotkih "I don't care about cookies", ki pa v tem primeru ne povzroča težave).

Gre za to, da je najbolj praktično, če se zahteva za popravek sporoči na forumu tistega seznama filtrov, ki je težavo povzročil. Če tam ne bo odziva, pa lahko to zgoraj omenjeno rešitev dodam tudi na slovensko listo.

P.S. Če se ne motim, je primer direktne povezave do prijavnega zaslona, kjer prihaja do te blokade, recimo tale (za dostopanje do Oblaka 365 preko storitve Arnes AAI): https://ds.aai.arnes.si/simplesaml/saml2/sp/idpdisco.php?entityID=https%3A%2F%2Fo365.arnes.si%2Fshibboleth&return=https%3A%2F%2Fo365.arnes.si%2FShibboleth.sso%2FLogin

**Comment by randomtroller** [comment]
EasyList cookie

**Comment by betterwebleon** [comment]
Težava javljena na pripadajoči forum:
https://forums.lanik.us/viewtopic.php?f=64&t=45556

Če pa ustreznega popravka slučajno ne bi dodali na EasyList Cookie List, ga bom dodal na slovensko listo.

**Comment by betterwebleon** [comment]
Urejeno.
