### ISSUE TITLE
get-native.eu

### ISSUE THREAD

**Issue by randomtroller** [betterwebleon/slovenian-list#20]
`||get-native.eu^$third-party`
Primer: vecer.com

Najslabsi je t.get-native.eu ki vrze URL strani na njihov server, aka third party tracker.
Na spletni strani get-native.eu pise "native advertising technology"
Se veliko pojavlja na popularnih slovenskih spletnih straneh

**Comment by betterwebleon** [comment]
Hvala, urejeno: 0ddbc18
