### ISSUE TITLE
partis

### ISSUE THREAD

**Issue by randomtroller** [betterwebleon/slovenian-list#21]
`||leadsdome.com$third-party`

Gre za se eno oglasevalno agencijo. Requesti na to domeno niso blokirani ampak bi morali biti ker vrze XHR na /get z veliko GET parametri s informacijami o tvojem operacijskem sistemu, IP naslov, user agent in URL strani.

`||propellente.net$third-party`

Na pol blokirana ampak bi jo morali v celoti ker nima smisla da sploh kontaktiramo to domeno. Gre spet za neke reklame

**Comment by betterwebleon** [comment]
Hvala, urejeno: 021f438
