### ISSUE TITLE
ceneje.si, mimovrste.com

### ISSUE THREAD

**Issue by randomtroller** [betterwebleon/slovenian-list#23]
Neuporabni logi
```
||ceneje.si/*/LogPageView
||ceneje.si/*/GetProductAds
||ceneje.si/*/LogBadgeBrandSellers
||ceneje.si/*/LogAbraModule
||ceneje.si/*/LogTopProductImpressions
```
"PageSpeed" aka zbiranje informacij
`||ps.ceneje.si$third-party`

Skripte iz te domene za še neko dodatno sledenje ki ga že blokiramo zato ni treba da kontaktiramo to domeno
`||chimpstatic.com$third-party`

neuporabni requesti na te domene, verjetno za analitiko
```
||mallgroup.com$third-party,domain=mimovrste.com
||mg-marxy.mall.cz$third-party,domain=mimovrste.com
```
Če ta skripta ni blokirana bo mimovrste v neskončnost probal kontaktirati tiste domene
`||mimovrste.com/*/marxy.js`

Zbiranje podatkov, lahko bi predlagali ta filter na bolj splošen seznam
`||databreakers.com$third-party`

**Comment by betterwebleon** [comment]
Lahko posreduješ stran, kjer se pojavlja sledenje iz domene `ps.ceneje.si`? Sledenja iz nje nisem zasledil na ceneje.si.
Ostalo je urejeno: 2a6b3ca
