### ISSUE TITLE
Splošen filter blokiranja reklam na partisu

### ISSUE THREAD

**Issue by randomtroller** [betterwebleon/slovenian-list#24]
Partis zdaj pridobiva reklame iz domene `ad.exilio.net`. Pomislil sem, da bi lahko uporabili `||ad.*$domain=partis.si` za blokiranje večine reklamnih omrežij v prihodnosti

**Comment by betterwebleon** [comment]
Hvala za predlog. Zaenkrat naj vseeno ostane pri eksaktnih filtrih. Prednost tega načina je ta, da se lažje zaznavajo nove domene z oglasi, ki jih v primeru splošnega filtra morda ne bi (takoj) zaznal in na seznam dodal kot splošne third-party vnose, bi pa bile te domene hkrati "aktivne" tudi na drugih portalih (in torej ne samo na partisu).

Sicer pa je urejeno: 2a6b3ca
