### ISSUE TITLE
Banner na bolhi

### ISSUE THREAD

**Issue by randomtroller** [betterwebleon/slovenian-list#25]
`||bolha.com/*/banneri/`
na https://www.bolha.com/prodaja-stanovanja

**Comment by randomtroller** [comment]
Update: izgleda, da so dodali še banner za mimovrste, ki ga lahko najdemo na glavni strani. V tem primeru dodaj še `www.bolha.com##.wrap-notification > .wrap-notification:has(img[src*="/banneri/"])` ampak pusti network filter, ker ni treba da nalagamo bannerje

**Comment by betterwebleon** [comment]
Urejeno: 4227c72
Hvala!
