### ISSUE TITLE
||pipe.aria.microsoft.com/collector/

### ISSUE THREAD

**Issue by crssi** [betterwebleon/slovenian-list#27]
Verjetno je filter `||pipe.aria.microsoft.com/collector/` prišel pomotoma na to listo, ki je sicer bolj primeren za kakšno splošno listo in ne slovensko?

Lep pozdrav

**Comment by betterwebleon** [comment]
Urejeno: ef7f077
Filter je bil očitno pred leti namenjen za blokado sledenja na katerem od slovenskih portalov. Sedaj kot kaže ni več potrebe po tem filtru in je odstranjen.

Hvala!
