### ISSUE TITLE
Sumljiv inartc.mp4 iz zurnal24.si

### ISSUE THREAD

**Issue by randomtroller** [betterwebleon/slovenian-list#28]
Na strani [forum.over.net](https://forum.over.net). Kontaktira domeno zurnal24.si kjer pridobi `inartc.mp4` ali `inartc.webm`. Datoteki sta neuporabni in video je samo črn dolg manj kot sekundo. Je to kakšen poskus sledenja? Tehnično je in nima smisla, da nalagamo te videoposnetke. Predlagam `||zurnal24.si/banners/*/inartc`

**Comment by betterwebleon** [comment]
Urejeno: ef7f077
Hvala!
