### ISSUE TITLE
Nov banner na Bolhi

### ISSUE THREAD

**Issue by randomtroller** [betterwebleon/slovenian-list#29]
Dodali so nov banner od NLBja in prejšnji filtri ga ne blokirajo. `www.bolha.com##.wrap-main > div > div:has(img[src*="banneri"]):has(a[href^="https://bit.ly"])` bi moral blokirati tudi bannerje v prihodnosti, ker do zdaj so vsi imeli sliko ki je v URLju imela banneri in link na bit.ly, ker morajo nekako sledit stevilo klikov. (razen, če spremenijo html strukturo bannerja)

**Comment by betterwebleon** [comment]
Urejeno: 2c76c60
Hvala!
