### ISSUE TITLE
bolha.com is broken

### ISSUE THREAD

**Issue by kanecko** [betterwebleon/slovenian-list#3]
Hello,
any results page will not load images on normal listings as well as the cost sliders do not appear.

Example: http://www.bolha.com/iskanje?q=law

**Comment by betterwebleon** [comment]
Hello,
it looks fine here ([screenshot](http://i.imgur.com/xCnymmF.png)). Do you have any special filters / filter lists in your blocker?

**Comment by kanecko** [comment]
Ugh. Yeah! I'll investigate further and close the issue soon. 
Sorry for the false alarm.

**Comment by betterwebleon** [comment]
No problem. :)
I can offer you some help regarding uBlock Origin. Hopefully you are using it as well. It's the recommended content blocker - better than AdBlock, Ghostery, Adguard…

To solve your problem with uBlock Origin (or also uBlock):
1. check which rule(s) cause trouble --> [follow these steps](http://i.imgur.com/jymNE50.png) for using the _logger_
2. edit your custom filters --> [follow these steps](http://i.imgur.com/KhwazZw.png) for entering »_My filters_« pane
3. review your filter lists in the »_3rd-party filters_« pane
4. check there are no unwanted rules in the »_My rules_« pane (besides »_My filters_«)

Here is additional information about using:
- [uBlock Origin logger](https://github.com/gorhill/uBlock/wiki/The-logger)
- [uBlock Origin in general](https://github.com/gorhill/uBlock/wiki)

If this doesn't help, you can also check elsewhere. For instance, review:
- other installed add-ons (if you have installed any),
- hosts file (if you have modified it) etc.

**Comment by kanecko** [comment]
Thanks! I've reported the error to the right audience: https://forums.lanik.us/viewtopic.php?f=64&t=35961
Now to watch as they don't give a damn! :D

**Comment by betterwebleon** [comment]
Great, nice to hear you found the issue. I am only using Enhanced Tracking List from Fanboy, so I couldn't see it. Otherwise I would have already reported it.
Don't worry they are good folks, they'll fix it. Just wait for a few days, because they have a bunch of work. And even in the worst case scenario, I can still add the exception rule to the SVN list. :)
