### ISSUE TITLE
Redirect spletne strani v slovenščini, onesnaženje Google iskanja

### ISSUE THREAD

**Issue by randomtroller** [betterwebleon/slovenian-list#30]
Živijo, prišel sem do nekaterih spletnih strani ki imajo več sto tisoč Google rezultatov. Te spletne strani se prikažejo, ko iščeš nekaj v slovenščini. Uporabljajo domeno, ki je sestavljena iz dveh naključnih besed iz slovarja, da je več možnosti, da nekdo klikne na nje. Iskanje Google za `site:bonbonijezero.xyz`pokaže, da ima ta stran 300 tisoč zadetkov. Stran te prevsmeri na razne nagrade in podobne fore. Mislim, da bi morale biti v celoti blokirane. Takih strani je 4, vse od iste osebe/skupine:

```
||bonbonijezero.xyz^
||sladicagora.xyz^
||kruhzgodovina.xyz^
||mandljigeografija.xyz^
```
Bom naredil nov issue, če najdem še kakšno.

**Comment by randomtroller** [comment]
Update: našel še 6:
```
||zajtrkhisa.xyz^
||kuminaluna.xyz^
||piscanecmatematika.xyz^
||hranavrt.xyz^
||maslootok.xyz^
||clublwd.nl^
```

**Comment by betterwebleon** [comment]
Hvala za javljen seznam, dodano: 22d4848

Če se bo nabralo še več tovrstnih vnosov, se lahko čez čas seznam vseh domen javi še na relevantno listo, kot je recimo "uBlock filters – Badware risks".
