### ISSUE TITLE
Prijavnica na telekom.si ne deluje

### ISSUE THREAD

**Issue by crssi** [betterwebleon/slovenian-list#31]
URL: `https://www.telekom.si/poslovni-uporabniki/ponudba/resitve-za-podjetja/izobrazevalni-center/seznam-izobrazevanj/posamezno-izobrazevanje/MS-030T00`

RULE: `||telekom.si/*/track.js`

Lep pozdrav 😄

**Comment by betterwebleon** [comment]
Urejeno: 22d4848
Hvala! :)
