### ISSUE TITLE
24ur.com | Video

### ISSUE THREAD

**Issue by brajkovicpavle** [betterwebleon/slovenian-list#34]
Na spletni strani 24ur.com so začeli intenzivno blokirati uBlock filtre, ki preprečujejo prikaz oglasov pre-roll, mid-roll in post-roll na videoposnetkih.

Zaenkrat pa je edini filter, ki še blokira oglase na videoposnetkih, naslednji:

@@||ads.api.24ur.si/adserver/$object,domain=www.24ur.com

**Comment by betterwebleon** [comment]
Hvala za info. Prosil bi, če lahko osvežiš vse svoje sezname filtrov in nato ponovno preveriš stanje na 24ur.com. Sumim, da je bila v vmesnem času nepravilnost odpravljena že na enem od drugih seznamov filtrov. Meni namreč s podobljenimi filtri videi na portalu delujejo normalno.

Če uporabljaš uBlock Origin, vse sezname filtrov posodobiš v nastavitvah razširitve: klik na ikono uBlock Origin > v meniju klik na desni gumb s koleščki ([viden na tej sliki skrajno desno](https://user-images.githubusercontent.com/95879668/161408418-d20fc334-8dae-409a-9df9-7cc9bacc33c6.png)) > zavihek "Filtri tretjih oseb" > klik na gumb "Sprosti celoten predpomnilnik" > nato klik na gumb "Posodobi zdaj". Če bodo za tem po osvežitvi portala 24ur.com še vedno težave s prikazom videov, prosim za povratno informacijo s priloženo povezavo do problematičnega videa.
