### ISSUE TITLE
"showing results for" messages on google are incorrectly blocked

### ISSUE THREAD

**Issue by DetachHead** [betterwebleon/slovenian-list#35]
this is caused by the following rule:
![image](https://github.com/betterwebleon/slovenian-list/assets/57028336/f393438c-725c-47e6-b52e-3254bf967d5b)

# list enabled
![image](https://github.com/betterwebleon/slovenian-list/assets/57028336/30e249db-5ffd-4095-ab61-edc499509230)

# list disabled
![image](https://github.com/betterwebleon/slovenian-list/assets/57028336/c2489e70-71c8-463e-a63e-b628db6f9773)

**Comment by betterwebleon** [comment]
Hello, thanks for info. Fixed in [ecc9b04](https://github.com/betterwebleon/slovenian-list/commit/ecc9b0494525414d820ec8ee69d6330f7c1c4ff5).
