### ISSUE TITLE
24ur.com

### ISSUE THREAD

**Issue by Denny-89** [betterwebleon/slovenian-list#37]
Na 24ur.com se že nekaj časa čisto na vrhu, na desni strani in na dnu člankov prikazuje neka nova nesnaga.

Za player na vrhu ter slike označene z "OGLAS" na desni strani in na dnu:
```
www.24ur.com##.adplayer
www.24ur.com##.adcontent.relative
www.24ur.com##div.sidebar__box:nth-of-type(8)
```

za blokado celotnega spodnjega ProAd frama s predlogi člankov in trackingom:
`www.24ur.com###proad`

Naj še kdo preveri, da ti filtri slučajno česa ne pokvarijo...

**Comment by betterwebleon** [comment]
Hvala za sporočilo. Navedeno naj bi bilo (v navezi z listama EasyList in EasyPrivacy) urejeno z [dc1beef](https://github.com/betterwebleon/slovenian-list/commit/dc1beef1b155f839e1b05742fe1584ee990faa6d).

Če so še kakšne težave, prosim za primer strani. Opomba: težava z blokado predvajanja videov na 24ur.com je že objavljena tukaj:
https://forums.lanik.us/viewtopic.php?t=48397-24ur-com

**Comment by betterwebleon** [comment]
Samo za info, po vnovičnem testiranju je dodanih še nekaj pravil: [37cf6e7](https://github.com/betterwebleon/slovenian-list/commit/37cf6e732a26c11cb20590c1d11b3f3ac0d55ae7). Zdaj bi moralo biti ok.
