### ISSUE TITLE
replace "uBlock" to "Nano Adblocker"

### ISSUE THREAD

**Issue by ghost** [betterwebleon/slovenian-list#5]
![2018-06-09-betterwebleon_slovenian-list_ slovenian cosmetic and tracking filters for ublock](https://user-images.githubusercontent.com/5884000/41193756-4794ba34-6c11-11e8-9d47-d3318dbeb99e.png)

<https://github.com/uBlockAdmin/uBlock/commit/76b89c0a22d20f3a66d7feab14e024f56ca65539>

**Comment by betterwebleon** [comment]
Thanks for your feedback. Readme file is outdated as well, but it will be (further) updated in the future.
