### ISSUE TITLE
Remove onl-microsite

### ISSUE THREAD

**Issue by tedomedo** [betterwebleon/slovenian-list#6]
Po slovensko: na vrhu strani 24ur.com se vidi bližnjice do bibaleze, moški svet, vizita in tako naprej. Ta filter teh bližnjic ne kaže. Cela skupina teh bližnjic je v ##onl-microsite, znotraj tega pa še ##.upscore-pos-7.focus.

**Comment by betterwebleon** [comment]
Hvala za sporočilo. Popravljeno: 72ef430

Razloga za blokado teh bližnjic sta (bila) dva. Prvič, na manjših zaslonih se zmanjša preglednost strani, ker je pasica dokaj visoka. Drugič, občutno se podaljša čas nalaganja strani. Kljub temu odstranjujem filter, ker pri tem ne gre za "pravo" reklamo, pa tudi zato, ker se po lanski prenovi portala 24ur.com vse skupaj vseeno naloži hitreje.

Ta logika bo odslej torej veljala tudi za druge portale, npr. za cekin.si in zadovoljna.si – tudi na teh je odslej pri vrhu vidna pasica.

Sicer si moram enkrat vzeti čas in posodobit celotno listo in readme file, ker sta že malo za časom. :)
