### ISSUE TITLE
##.embed--component blokira twitter na...

### ISSUE THREAD

**Issue by crssi** [betterwebleon/slovenian-list#8]
...strani https://cekin.si/koristno/delo-zaposlenih-v-zdravstvu-novi-koronavirus.html

**Comment by betterwebleon** [comment]
Urejeno: 6f5335d
Hvala!

**Comment by crssi** [comment]
Ni pene. 😄 

Imam še nekaj svojih SLO orientiranih.
Če želiš lahko osprem nov issue in jih copy/pasteam?

lp

**Comment by betterwebleon** [comment]
Lahko, bi bilo dobrodošlo, ko utegneš. 👍 Še posebej, če gre za kakšne nove strani. 🙂 Obstoječih vnosov že nekaj časa nisem osveževal, je pa v planu za prihodnje.

Lp
